baseURL: "http://taptiger.netlify.app"
title: TapTiger's Blog
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archives
          url: /archives/
          weight: 5
        - name: Tags
          url: /tags/
          weight: 10

  l2:
    languageName: "Gaeilge"
    weight: 2
    title: Blag TapTiger
    profileMode:
      enabled: true
      title: Fáilte!
      # imageUrl: "#"
      # imageTitle: my image
      subtitle: Níl mórán eagraithe agam anseo go fóill, ach táim ag tnuth le go bheas roinnt le léamh uaim as Gaeilge freisin.
      # buttons:
      #   - name: Blog
      #     url: /posts
      #   - name: Tags
      #     url: /tags

params:
  env: production
  description: "A blog following the Game Off 2020 efforts of taptiger"
  author: taptiger
  # author: ["Me", "You"] # multiple authors
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  displayFullLangName: true
  # images: ""
  # assets:
  #   favicon: '<path / external url>'

  profileMode:
    enabled: false
    title: TapTiger ProfileMode
    imageUrl: "#"
    imageTitle: my image
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog! I am building a game for Game Off 2020. Here's how I'm getting there.

  socialIcons:
    - name: github
      url: "https://github.com/taptiger"
    - name: twitter
      url: "https://twitter.com/taptigergames"
    - name: reddit
      url: "https://www.reddit.com/user/taptiger"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true